services:
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:5001"
  backend:
    build: ./backend/
    ports:
      - "5001:5000"
